### ISSUE TITLE
Request for code to reproduce paper results

### ISSUE THREAD

**Issue by basic-learn-er** [Walterkd/diffusion-refine-sketch2point#1]
Hello,

I have been trying to reproduce the results from your paper, but have been unable to do so successfully based on the details provided in the paper.

Specifically, the experimental setup described in the paper differs from common practices in sketchsampler[1], for the community usually use 8192 points, and you chose 692 in the paper, which is quite confusing. Without access to the original code, it is difficult for me to align my experiments with yours. It is also confusing that you did not compare your method with methods designed specially for sketch-to-point, but chose to compare with the general image-to-point methods in the main document.

I wanted to check if you have plans to open source the code for this paper? Being able to inspect the exact model implementations and training scripts would greatly help my efforts to replicate the results.

Opening up the code would also make it easier for others to build on your work in the future.

Please let me know if and when you plan to release the code. I'm happy to provide more details on my reproduction efforts as well if useful.

Thank you for your consideration!

[1] Gao C, Yu Q, Sheng L, et al. SketchSampler: Sketch-Based 3D Reconstruction via View-Dependent Depth Sampling[C]//European Conference on Computer Vision. Cham: Springer Nature Switzerland, 2022: 464-479.

**Comment by Walterkd** [comment]
Thank you for your attention. 
Sorry, I didn't refer SketchSampler before submitting my paper, my perception before this was that people usually use 2048 or 1024 points, but that many points is too big for our limited GPU memory, so we downscale to 692 points, which speeds up our training time, inference time and iteration time. However this number of points can be modified in the settings.

As for the baselines for comparison, we did not take this into consideration when we wrote the paper at that time, and some reviewers pointed it out in the rebuttal stage, and we also added it in our rebuttal, but did not put it into the main document.

Yes, we plan to open the code, but it won't be in the near future, I will be organizing and refactoring the code during the time finishing my final year design, which will be 2024, lately I've been occupied with my internship and PhD apply thing, so I may not have the time to do the open source thing. If you're in a hurry, you can refer to another work LAS-Diffusion [1] that's similar to ours but better, they can do a better job of achieving what we're trying to do. So I can't tell you exactly when it will be open source, but there will be plans to go open source in the future.

[1] Zheng X Y, Pan H, Wang P S, et al. Locally attentional sdf diffusion for controllable 3d shape generation[J]. arXiv preprint arXiv:2305.04461, 2023.
